/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pol Karaga Roselló (https://sketchfab.com/Noouk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/astro13-flying-b3877ab8dc27411bb21cc9f6c883e96c
title: Astro13_Flying
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/astronaut.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="eac333c4ad9248fd9ae1e4dccb45a1a9fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="metarig" position={[-0.12, -150.81, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={145.9}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Default.001']} skeleton={nodes.Object_9.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/astronaut.gltf')
